name: fastify-pretty-log
base: core22 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: a log formatter for fastify
description: |
  node my.fastify.app.js | fastify-pretty-log

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  fastify-pretty-log:
    plugin: rust
    source: .
    build-packages:
      - build-essential